spring:
  datasource:
    username: postgres
    password: Fly_2019
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
mybatis:
  type-aliases-package: com.yizhile.domain
  mapper-locations: com/yizhile/mapper/*.xml